apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: docker.io/ydeyeq/node-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
